"""RoadGen3D backend package."""

from .design_rules import extend_constraint_set, list_constraint_profiles, load_constraint_set
from .compliance_eval import compute_compliance, evaluate_compliance_batch
from .decoder import PlaceholderVoxelDecoder
from .decoder_shapee import ShapeEDecoder, ShapeEDecoderError
from .embedder import ClipTextEmbedder, ModelLoadError
from .entrance_analysis import (
    CarriagewayBoundary,
    PlacedAssetRegistry,
    compute_entrance_openness,
    compute_noise_shielding,
    evaluate_all_entrances,
    score_entrance_impact,
)
from .eval_metrics import (
    aggregate_scene_rows,
    compare_mode_reports,
    compute_cross_section_feasibility,
    compute_dropped_slot_rate,
    compute_editability,
    compute_explainability,
    compute_latency_ms_per_instance,
    compute_mean_entrance_openness,
    compute_mean_noise_shielding,
    compute_overlap_rate,
    compute_rule_satisfaction_rate,
    compute_topology_validity,
    evaluate_topk_category_hits,
)
from .index_store import FaissIndexStore
from .latent_store import LatentStore, load_asset_records
from .layout_features import CandidateDescriptor, PolicyFeatureContext, build_candidate_feature
from .layout_policy import LayoutPolicyMLP, LayoutPolicyRuntime, PolicyTrainConfig
from .layout_solver import LayoutSolverRuntime, solve_layout
from .metaurban_procedural import (
    MetaUrbanProceduralConfig,
    build_metaurban_layout_payload,
    build_metaurban_segment_graph,
    resolve_metaurban_block_sequence,
    sample_metaurban_block_sequence,
    write_metaurban_layout_payload,
)
from .milp_solver import solve_candidate_assignment
from .osm_ingest import fetch_osm_data, parse_osm_features, project_to_local
from .osm_segment_graph import build_segment_graph
from .parametric_assets import (
    BenchParams,
    BuildingParams,
    GenerationQualityMetrics,
    GenerationRequest,
    LampParams,
    ParametricAssetResult,
    TreeParams,
    generate_parametric_asset,
)
from .pipeline import M1Pipeline
from .placement_zones import PlacementContext, build_placement_context
from .poi_rules import ConstraintResult, load_rule_set, score_placement
from .road_discovery import DiscoveredRoad, discover_poi_roads, write_discovered_roads_jsonl
from .program_generator import (
    ProgramGeneratorRuntime,
    ProgramTrainConfig,
    split_program_samples_by_scene,
    train_program_generator,
    vectorize_program_input,
)
from .runtime_device import resolve_device_backend, resolve_torch_device
from .street_layout import compose_street_scene
from .street_program import infer_street_program
from .theme_buildings import infer_theme_segments
from .types import (
    AssetRecord,
    BuildingFootprint,
    BuildingPlacementPlan,
    ConstraintSet,
    DesignRuleSpec,
    EntranceAssessment,
    InventorySummary,
    LayoutConflict,
    LayoutEdit,
    LayoutSlotPlan,
    LayoutSolverInput,
    LayoutSolverResult,
    PipelineResult,
    PlacedAsset,
    PrepareWorkspaceResult,
    ProductionStepRecord,
    ProgramGenerationInput,
    ProgramGenerationResult,
    RetrievalHit,
    RoadSegmentBand,
    RoadSegmentEdge,
    RoadSegmentGraph,
    RoadSegmentNode,
    RuleEvaluation,
    SceneEntranceReport,
    StepResult,
    StreetBand,
    StreetComposeConfig,
    StreetComposeResult,
    StreetPlacement,
    StreetProgram,
    ThemeSegment,
    WorkspaceReadiness,
)
from .voxel_export import export_voxel_meshes

__all__ = [
    "AssetRecord",
    "BenchParams",
    "BuildingFootprint",
    "BuildingParams",
    "BuildingPlacementPlan",
    "CandidateDescriptor",
    "CarriagewayBoundary",
    "ClipTextEmbedder",
    "ConstraintSet",
    "ConstraintResult",
    "DesignRuleSpec",
    "DiscoveredRoad",
    "EntranceAssessment",
    "FaissIndexStore",
    "GenerationQualityMetrics",
    "GenerationRequest",
    "LayoutPolicyMLP",
    "LayoutPolicyRuntime",
    "LayoutSolverRuntime",
    "LayoutConflict",
    "LayoutEdit",
    "LayoutSlotPlan",
    "LayoutSolverInput",
    "LayoutSolverResult",
    "LatentStore",
    "M1Pipeline",
    "MetaUrbanProceduralConfig",
    "ModelLoadError",
    "LampParams",
    "PipelineResult",
    "ParametricAssetResult",
    "PlacedAsset",
    "PlacedAssetRegistry",
    "PlacementContext",
    "PolicyFeatureContext",
    "PolicyTrainConfig",
    "PrepareWorkspaceResult",
    "PlaceholderVoxelDecoder",
    "ProductionStepRecord",
    "ProgramGenerationInput",
    "ProgramGenerationResult",
    "ProgramGeneratorRuntime",
    "ProgramTrainConfig",
    "RetrievalHit",
    "RoadSegmentBand",
    "RoadSegmentEdge",
    "RoadSegmentGraph",
    "RoadSegmentNode",
    "SceneEntranceReport",
    "ShapeEDecoder",
    "ShapeEDecoderError",
    "RuleEvaluation",
    "StepResult",
    "StreetBand",
    "StreetComposeConfig",
    "StreetComposeResult",
    "StreetPlacement",
    "StreetProgram",
    "ThemeSegment",
    "TreeParams",
    "WorkspaceReadiness",
    "aggregate_scene_rows",
    "build_candidate_feature",
    "build_metaurban_layout_payload",
    "build_metaurban_segment_graph",
    "build_placement_context",
    "build_segment_graph",
    "compare_mode_reports",
    "compute_compliance",
    "compute_cross_section_feasibility",
    "compute_dropped_slot_rate",
    "compute_editability",
    "compute_entrance_openness",
    "compute_explainability",
    "compute_latency_ms_per_instance",
    "compute_mean_entrance_openness",
    "compute_mean_noise_shielding",
    "compute_noise_shielding",
    "compute_overlap_rate",
    "compute_rule_satisfaction_rate",
    "compute_topology_validity",
    "compose_street_scene",
    "discover_poi_roads",
    "evaluate_all_entrances",
    "extend_constraint_set",
    "evaluate_compliance_batch",
    "evaluate_topk_category_hits",
    "export_voxel_meshes",
    "fetch_osm_data",
    "generate_parametric_asset",
    "infer_theme_segments",
    "infer_street_program",
    "InventorySummary",
    "list_constraint_profiles",
    "load_asset_records",
    "load_constraint_set",
    "load_rule_set",
    "parse_osm_features",
    "project_to_local",
    "resolve_device_backend",
    "resolve_metaurban_block_sequence",
    "resolve_torch_device",
    "sample_metaurban_block_sequence",
    "score_entrance_impact",
    "score_placement",
    "solve_candidate_assignment",
    "solve_layout",
    "split_program_samples_by_scene",
    "train_program_generator",
    "vectorize_program_input",
    "write_metaurban_layout_payload",
    "write_discovered_roads_jsonl",
]
