"""Shared scene presets for Workbench and test pipeline."""

from __future__ import annotations

COURSE_DELIVERY_CONFIG_PATCH: dict[str, object] = {
    "layout_solver": "hybrid_milp_v1",
    "program_generator": "heuristic_v1",
    "allow_solver_fallback": True,
    "asset_scale_mode": "canonical_v1",
    "asset_curation_mode": "scene_ready_first",
    "curated_street_assets_profile": "fixed_hq_v1",
    "scene_texture_mode": "topdown_tiles_v1",
    "topdown_render_mode": "design_tiles_v1",
    "render_preset": "axonometric_board_v1",
    "beauty_mode": "presentation_v1",
}

SCENE_PRESETS: list[dict] = [
    {
        "id": "pedestrian_friendly",
        "name": "步行友好",
        "nameEn": "Pedestrian Friendly",
        "description": "行人优先，安全舒适",
        "icon": "🚶",
        "color": "#4CAF50",
        "prompt": "步行安全，全龄友好的完整街道，安静、安全、舒适",
        "configPatch": {
            **COURSE_DELIVERY_CONFIG_PATCH,
            "street_furniture_profile": "pedestrian_friendly",
            "street_furniture_profile_source": "manual",
            "street_furniture_profile_confidence": 1.0,
            "street_furniture_profile_reasons": ("preset:selected",),
            "design_rule_profile": "pedestrian_priority_v1",
            "objective_profile": "balanced",
            "density": 0.5,
            "ped_demand_level": "high",
            "bike_demand_level": "medium",
            "transit_demand_level": "medium",
            "vehicle_demand_level": "low",
        },
    },
    {
        "id": "commercial_vitality",
        "name": "商业活力",
        "nameEn": "Commercial Vitality",
        "description": "商业活跃，人流密集",
        "icon": "🛍️",
        "color": "#FF9800",
        "prompt": "商业活跃的街道，商业设施密集，人流穿梭",
        "configPatch": {
            **COURSE_DELIVERY_CONFIG_PATCH,
            "street_furniture_profile": "commercial_vitality",
            "street_furniture_profile_source": "manual",
            "street_furniture_profile_confidence": 1.0,
            "street_furniture_profile_reasons": ("preset:selected",),
            "design_rule_profile": "balanced_complete_street_v1",
            "objective_profile": "commerce",
            "density": 0.9,
            "ped_demand_level": "high",
            "bike_demand_level": "medium",
            "transit_demand_level": "high",
            "vehicle_demand_level": "medium",
        },
    },
    {
        "id": "transit_priority",
        "name": "公交优先",
        "nameEn": "Transit Priority",
        "description": "公交导向，换乘便利",
        "icon": "🚌",
        "color": "#2196F3",
        "prompt": "公交优先的街道，公交可达性高，换乘便利",
        "configPatch": {
            **COURSE_DELIVERY_CONFIG_PATCH,
            "street_furniture_profile": "transit_priority",
            "street_furniture_profile_source": "manual",
            "street_furniture_profile_confidence": 1.0,
            "street_furniture_profile_reasons": ("preset:selected",),
            "design_rule_profile": "transit_priority_v1",
            "objective_profile": "transit",
            "density": 0.85,
            "ped_demand_level": "high",
            "bike_demand_level": "medium",
            "transit_demand_level": "high",
            "vehicle_demand_level": "high",
        },
    },
    {
        "id": "park_landscape",
        "name": "公园景观",
        "nameEn": "Park Landscape",
        "description": "绿化为主，休闲舒适",
        "icon": "🌳",
        "color": "#8BC34A",
        "prompt": "公园景观街道，绿化丰富，自然生态，休闲舒适",
        "configPatch": {
            **COURSE_DELIVERY_CONFIG_PATCH,
            "street_furniture_profile": "park_landscape",
            "street_furniture_profile_source": "manual",
            "street_furniture_profile_confidence": 1.0,
            "street_furniture_profile_reasons": ("preset:selected",),
            "design_rule_profile": "pedestrian_priority_v1",
            "objective_profile": "greening",
            "density": 0.25,
            "ped_demand_level": "medium",
            "bike_demand_level": "medium",
            "transit_demand_level": "low",
            "vehicle_demand_level": "low",
        },
    },
    {
        "id": "quiet_residential",
        "name": "安静居住",
        "nameEn": "Quiet Residential",
        "description": "住宅区安静，绿树成荫",
        "icon": "🏠",
        "color": "#9C27B0",
        "prompt": "安静居住街道，绿树成荫，步行安全，适合全龄",
        "configPatch": {
            **COURSE_DELIVERY_CONFIG_PATCH,
            "street_furniture_profile": "quiet_residential",
            "street_furniture_profile_source": "manual",
            "street_furniture_profile_confidence": 1.0,
            "street_furniture_profile_reasons": ("preset:selected",),
            "design_rule_profile": "pedestrian_priority_v1",
            "objective_profile": "greening",
            "density": 0.35,
            "ped_demand_level": "high",
            "bike_demand_level": "medium",
            "transit_demand_level": "low",
            "vehicle_demand_level": "low",
        },
    },
    {
        "id": "balanced_complete",
        "name": "平衡街道",
        "nameEn": "Balanced Complete",
        "description": "各类使用者平衡",
        "icon": "⚖️",
        "color": "#607D8B",
        "prompt": "各类使用者平衡的完整街道，行人、自行车、公交、机动车和谐共处",
        "configPatch": {
            **COURSE_DELIVERY_CONFIG_PATCH,
            "street_furniture_profile": "balanced_complete",
            "street_furniture_profile_source": "manual",
            "street_furniture_profile_confidence": 1.0,
            "street_furniture_profile_reasons": ("preset:selected",),
            "design_rule_profile": "balanced_complete_street_v1",
            "objective_profile": "balanced",
            "density": 0.6,
            "ped_demand_level": "medium",
            "bike_demand_level": "medium",
            "transit_demand_level": "medium",
            "vehicle_demand_level": "medium",
        },
    },
]

__all__ = ["COURSE_DELIVERY_CONFIG_PATCH", "SCENE_PRESETS"]
